---
title: "Damage Versus Armor: The Best and Worst Unit for Every Unit"
output:   
  bookdown::html_document2:
    toc: yes
    toc_depth: 2
    number_sections: yes
pkgdown:
vignette: >
  %\VignetteIndexEntry{damage-versus-armor}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

```{r set-options-attach-packages, include = TRUE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)

library(battleRealms)
library(data.table)
library(cdata)
library(magrittr)
library(DT)

# create standard datatable function to be used in all tables in this post
show_datatable <- function(data) {
  data %>% 
    DT::datatable(
      rownames = FALSE,
      extensions = 'FixedColumns',
      options = list(
        pageLength = 50,
        scrollX = TRUE,
        scrollCollapse = TRUE,
        fixedColumns = list(leftColumns = 3),
        columnDefs = list(
          list(
            className = 'dt-center',
            targets = 0:(ncol(data) - 1)
          )
        )
      ),
      filter = list(position = 'top', clear = FALSE, plain = TRUE)
    )
}

```

# Data Preparation

```{r build-damage-vs-armor}

unit_damage_armor <- br_unit_stats[
  ,
  .(
    Name,
    Clan,
    MaxHealth,
    DamageClass,
    WeaponType,
    BaseDamage,
    ArmorAgainst,
    DamageMultiplier
  )
]

defender <- copy(unit_damage_armor)

attacker <- copy(unit_damage_armor)

setnames(
  defender, 
  old = names(unit_damage_armor), 
  new = paste0("Defender", names(unit_damage_armor))
)

setnames(
  attacker, 
  old = names(unit_damage_armor), 
  new = paste0("Attacker", names(unit_damage_armor))
)

damage_vs_armor <- attacker[
  defender, 
  on = c("AttackerDamageClass" = "DefenderArmorAgainst"), 
  allow.cartesian = TRUE
]

```

# Simulate Damage To Kills

```{r simulate-one-on-one}

damage_vs_armor[
  ,
  `:=`(
    AttackerToKill =
      DefenderMaxHealth / (AttackerBaseDamage * DefenderDamageMultiplier),
    DefenderToKill = 
      AttackerMaxHealth / 
      (
        DefenderBaseDamage * 
          fifelse(DefenderDamageClass == AttackerArmorAgainst, AttackerDamageMultiplier, 0.01)
      )
  )
]

damage_vs_armor[
  ,
  AttackerKills := AttackerToKill < DefenderToKill
]


```

